[package]
name = "means-to-an-end"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlite = "0.30.3"
tokio = { version = "1.24.1", features = ["full"] }
