[package]
name = "means-to-an-end"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
rusqlite = "0.28.0"
tokio = { version = "1.24.1", features = ["full"] }
tokio-rusqlite = "0.3.0"
